name: mlflow-demo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab=3.2
  - matplotlib=3.4
  - mlflow=1.21
  - scikit-learn=1.0
  - tensorflow=2.0
  - pip
  - pip:
    - jupyter_nbextensions_configurator==0.4.1
    - RISE==5.7
